application: cards-against-humanity
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: angular_app/app/index.html
  upload: angular_app/app/index\.html

- url: /partials
  static_dir: angular_app/app/partials

- url: /lib
  static_dir: angular_app/app/lib

- url: /css
  static_dir: angular_app/app/css

- url: /js
  static_dir: angular_app/app/js

- url: /.*
  script: home.app